version: '3.8'
services:
  webapp:
    container_name: desafio-skyline-dev
    build: 
      context: .
      dockerfile: dockerfile
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    restart: always 